services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: sdlc_app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  api:
    build: ..
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
