name: CI-CD

on:
  push:
    branches: [main, stage]
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/deploy-setup.yml

  backend-e2e-test:
    name: Backend E2E Test
    needs: setup
    uses: ./.github/workflows/deploy-backend-e2e.yml

  ui-test:
    name: UI Test
    needs: backend-e2e-test
    uses: ./.github/workflows/deploy-ui.yml

  appsec-check:
    name: AppSec Check
    needs: ui-test
    uses: ./.github/workflows/deploy-appsec.yml

  version-images:
    name: Version UI and API Images
    needs: appsec-check
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy-images.yml

  deployment:
    name: Deployment
    needs: version-images
    if: github.ref_type == 'branch'
    uses: ./.github/workflows/deploy-render.yml
    secrets: inherit
